Repository EnergyModelsX/EnergyModelsInvestments.jl, pull requests merged in 2024-05, with the labels that each got.

#19 Fix: OPEX contribution with varying length of strategic periods
  NEWS.md
  Project.toml
  ext/EMIGeoExt/model.jl
Labels: bug

#22 Add JOSS citation
  CITATION.cff
  README.md
Labels: documentation

#21 Adjustment to changes in Storage investments
  Project.toml
  docs/make.jl
  docs/src/how-to/update-models.md
  docs/src/index.md
  docs/src/library/public.md
  docs/src/manual/optimization-variables.md
  docs/src/manual/quick-start.md
  examples/geography.jl
  examples/network.jl
  ext/EMIGeoExt/model.jl
  src/EnergyModelsInvestments.jl
  src/checks.jl
  src/datastructures.jl
  src/legacy_constructor.jl
  src/model.jl
  src/utils.jl
  test/test_checks.jl
  test/test_model.jl
  test/utils.jl
Labels: enhancement

#23 Change how investment mode is handled
  examples/geography.jl
  examples/network.jl
  src/checks.jl
  src/datastructures.jl
  src/legacy_constructor.jl
  src/model.jl
  src/utils.jl
  test/test_checks.jl
  test/test_model.jl
  test/utils.jl
Labels: enhancement
