Repository EnergyModelsX/EnergyModelsInvestments.jl, pull requests merged in 2024-03, with the labels that each got.

#12 Bugfix in storage investments
  NEWS.md
  src/model.jl
Labels: bug

#13 Improvement of checks and tests
  NEWS.md
  Project.toml
  README.md
  src/checks.jl
  test/generate_data.jl
  test/runtests.jl
  test/test_checks.jl
  test/test_geo.jl
  test/test_lifetime.jl
  test/test_model.jl
  test/utils.jl
Labels: bug, enhancement

#14 Moved EMIGeoExt to a separate folder
  NEWS.md
  Project.toml
  ext/EMIGeoExt/EMIGeoExt.jl
  ext/EMIGeoExt/model.jl
  ext/EMIGeoExt/utils.jl
  ext/datastructures.jl
Labels: enhancement

#15 Bugfix: Correction of type ambioguity in start_cap for transmission modes
  NEWS.md
  ext/EMIGeoExt/utils.jl
Labels: bug

#16 Enhancement of checks
  NEWS.md
  Project.toml
  src/checks.jl
  test/test_checks.jl
  test/utils.jl
Labels: enhancement
